kvm_hosts:
  hosts:
    localhost
  vars:
    # variables for downloading cloud image the VM will be based off of
    base_image_name: "ubuntu-20.04-minimal-cloudimg-amd64.img"
    base_image_url:  "https://cloud-images.ubuntu.com/minimal/releases/focal/release/{{ base_image_name }}"
    # TODO think of a way to get sha256 sum from https://cloud-images.ubuntu.com/minimal/releases/focal/release/SHA256SUMS
    base_image_sha256sum: "e0807db19f85b231dbcb562096f2cf2f6afed6c5c4de981b2042811d44654be2"
    base_image_download_dest: '/tmp/{{ base_image_name }}'

    libvirt_pool_name: libvirt-img-pool
    libvirt_pool_dir: /var/lib/libvirt/images
    vm_volume_name: '{{ vm_name }}-vol'
    vm_volume_capacity_GB: '5'  # Gigabytes

    vnet_name: vnet01
    # TODO define gateway IP etc.

    vm_image_size_GB: '5'  # Gigabytes
    vm_name: serv-spring-petclinic
    vm_name_fqdn: serv-spring-petclinic
    vm_vcpus: '1'
    vm_ram_KiB: '500000'
    vm_net: '{{ vnet_name }}'
    vm_net_ip: 192.168.123.3
    vm_net_mask_CIDR: 24
    vm_net_gateway4: 192.168.123.1
    vm_net_nameservers:
      - 8.8.8.8

    ssh_authorized_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCX2bD/1l1d7kqjg0/u3FsgXReqwlPC2o+7LhVPZGFuZzst66dgh/PjmHGxaZeLlqwH2wEWSAxElkTELtWNmQi9/FrRVatp4B/dN5dhvI9nsayeMda9MZ4ZtuHGe6Te9ZoDd5/V4ujxtB8R75D/j5cbBYdaXW+WHRCumE80Jymmo0fGeWSIoAvxodeP5Xu9NoliHdo41BigLIOXU6JCavujFRvo+ag2Wxy2rR4oc7e+HGDXFZtXrRffRmTa5rLQD2KtRMKmFJyswr39x3kA/fKOKZ3oMlgpmJI5xNb1Ignn6FVAYNvi4rUCaEe6sWEIa+DKR0Mu+l1CG9xguU3wRJ5+aB2j5dZxRuI6QLQY67FRjeUVjXXPBCN+FjuHhoPVjRatqhQiAzrKb4KUOEzDOXDLgem785tzpPM7pKRy/Yzy2ZSXmOpEBjqhNam26VBZTXZYv6zxcK8Ypr2OekgUnbDjkms7cyGyuLcrMDPM8qCZkkCBYi8dSQQ+JYyuCydTVvU="
    admin_user_name: admin
    admin_user_password_hash: "$6$r2yiCi.YAtKRCBFK$S8//V8.dSLFRFRE5ft3nnzZlIOiAAz5UlQJOaMJQHr3EVi7ptaROQCfWlgCm63rV59s2CYm7DOYmILpYaAyl31" # plaintext password is "rootpw" (without quotes)
